### ISSUE TITLE
Multiple views support

### ISSUE THREAD

**Issue by gerbil** [artturik/network-policy-viewer#4]
Can't make two and more views working with different policies on the same page.. any suggestion how to approach this?

**Comment by artturik** [comment]
Hello, please update to latest component version - 2.0.2, it should fine now
https://github.com/artturik/network-policy-viewer/commit/d369891ef253990cd47d0292f4a1e8d6ad30d439#diff-9d33b3828f20810f77b2135bf1a49a13f47fbdb8a47fedbbf6e422c7f3ce1ba4
